[phases.setup]
nixPkgs = ["php", "nginx", "nodejs", "npm"]

[phases.install]
cmds = [
    "rm -rf node_modules package-lock.json",
    "npm install",
    "composer install --ignore-platform-reqs"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
