[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.env]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "development"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
